version: "3"
services:
  react-docker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/react-docker/node_modules
      - .:/app/react-docker #local folder reference from dir container
    stdin_open: true
